---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[hadoop::install]
      - recipe[flink::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[flink::jobmanager]
      - recipe[flink::taskmanager]
      - recipe[flink::wordcount]
    attributes:
         hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
         flink:
            jobmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            taskmanager:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
